version: '3.6'
services:
  wildfly:
    build:
      dockerfile: ./wildfly.dockerfile
      context: .
    image: junin17/wildfly
    container_name: wildfly
    ports:
      - "8080:8080"
    networks:
      - rede
    depends_on: 
      - "postgres"
  
  postgres:
    build:
      dockerfile: ./postgres.dockerfile
      context: .
    image: junin17/postgres
    container_name: postgres
    ports:
      - "1122:5432"
    networks: 
      - rede

networks: 
  rede:
    driver: bridge